bias: true
block_size: 1024
n_embd: 512  # scale7
n_head: 16  # scale7
# head_size = n_embd // n_head = 512 // 16 = 32
n_layer: 6  
n_query_groups: null
norm_class_name: LayerNorm
vocab_size: 50257
max_micro_batch_size: 6
