bias: true
block_size: 1024
n_embd: 640  # scale9
n_head: 16  # scale9
# head_size = n_embd // n_head = 640 // 16 = 40
n_layer: 6  
n_query_groups: null
norm_class_name: LayerNorm
vocab_size: 50257
max_micro_batch_size: 6
