# the `global` at all times must be a union of all other environments' listed variables

[global]
env_name = "warm_env_global"
workspace_path = "/work/dlclarge1/mallik-warmstarting/"
setup_script_path = "/work/dlclarge1/mallik-warmstarting/misc/setup_script.sh"
env_path="/work/dlclarge1/mallik-warmstarting/envs/"
venv_template_path = "/work/dlclarge1/mallik-warmstarting/venv_templates/"

env_root = "/work/dlclarge1/mallik-warmstarting/envs/"
data_root = "/work/dlclarge1/mallik-warmstarting/scale_and_warmstart/data/"
data_handler_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/configs/data_handlers/"
saws_root = "/work/dlclarge1/mallik-warmstarting/scale_and_warmstart/"
warms_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/"

results_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/results/"
slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/slurm_logs/"

train_template = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/configs/train_template.yaml"
mup_base_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/configs/width_only/mup"

[neeratyoy]
env_name = "nyoy_env"

saws_root = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/scale_and_warmstart/"
warms_root = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/warmstarting_exps/"
data_handler_root = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/warmstarting_exps/configs/data_handlers/"

slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/exps/talk/slurm_logs/"

train_template = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/warmstarting_exps/configs/train_template.yaml"
# train_template = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/exps/talk/configs/base_template_const.yaml"

[janowski]
env_name = "ym_env"

saws_root = "/work/dlclarge1/mallik-warmstarting/misc/janowski/code/scale_and_warmstart/"
warms_root = "/work/dlclarge1/mallik-warmstarting/misc/janowski/code/warmstarting_exps/"
data_handler_root = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/warmstarting_exps/configs/data_handlers/"

slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/misc/janowski/exps/post_shitty_draft/slurm_logs/"

train_template = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/code/warmstarting_exps/configs/train_template.yaml"
# train_template = "/work/dlclarge1/mallik-warmstarting/misc/neeratyoy/exps/talk/configs/base_template_const.yaml"

[johannes]
env_name = "warm_env_hogj"

saws_root = "/work/dlclarge1/mallik-warmstarting/misc/johannes/scale_and_warmstart/"
warms_root = "/work/dlclarge1/mallik-warmstarting/misc/johannes/warmstarting_exps/"
data_handler_root = "/work/dlclarge1/mallik-warmstarting/misc/johannes/warmstarting_exps/configs/data_handlers/"

results_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/results/"
slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/misc/johannes/slurm_logs/"

train_template = "/work/dlclarge1/mallik-warmstarting/misc/johannes/warmstarting_exps/configs/train_template.yaml"

[johannes-local]

saws_root = "/Users/hogj/Documents/warmstarting/scale_and_warmstart"
warms_root = "/Users/hogj/Documents/warmstarting/warmstarting_exps"
data_handler_root = "/Users/hogj/Documents/warmstarting/warmstarting_exps/configs/data_handlers"
data_root = "/Users/hogj/Documents/warmstarting/scale_and_warmstart/data"
results_root = "/Users/hogj/Documents/warmstarting/warmstarting_exps/results"
slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/misc/neeratyoy/exps/slurm_logs/"

train_template = "/Users/hogj/Documents/warmstarting/warmstarting_exps/configs/train_template.yaml"

[heri]
env_name = "warm_env_heri"

saws_root = "/work/dlclarge1/mallik-warmstarting/misc/heri/code/scale_and_warmstart/"
warms_root = "/work/dlclarge1/mallik-warmstarting/misc/heri/code/warmstarting_exps/"
data_handler_root = "/work/dlclarge1/mallik-warmstarting/misc/heri/code/warmstarting_exps/configs/data_handlers/"

results_root = "/work/dlclarge1/mallik-warmstarting/warmstarting_exps/results/"
slurm_logs_root = "/work/dlclarge1/mallik-warmstarting/misc/heri/slurm_logs/"

train_template = "/work/dlclarge1/mallik-warmstarting/misc/heri/code/warmstarting_exps/configs/train_template.yaml"
