warmstart_config_path: null
warmstart_config:
  activate: false
  base_model_path: /work/dlclarge1/mallik-warmstarting/warmstarting_exps/results/shitty_draft/slimpajama/block=1024_depth=6/baseline/sp/constLR/scale0
  warmstart_type: slice
  warmstarting_args: 
    use_init_std_as_perturb: false
  # warm_type: zeros
  # shrinkage_factor: 1
  # perturbation_sigma: 0.5

block_size: 1024
model_config_path: null
model_config:
  bias: true
  block_size: 1024
  n_embd: 192
  n_head: 8
  n_layer: 6
  norm_class_name: LayerNorm
  vocab_size: 50257

mup_base_scales: null
mup_base_shape_path: null

torch_scheduler: null
torch_scheduler_args: null
max_lr: 0.01
min_lr: 0
adam_beta_1: 0.9
adam_beta_2: 0.95
adam_eps: 1.0e-08
warmup_fraction: null
cooldown_fraction: null
cooldown_type: linear

independent_wd: true
weight_decay: 0
weight_init_type: null
z_loss_eps: null

devices: 1
micro_batch_size: 9
accumulation_iters: 1
max_micro_batch_size: null

clip_max_norm: null
clip_max_val: null

global_log_step: 1
tracked_metrics:
  gradient_norm_per_layer: 5
  l1_norm_per_layer: 5
  l2_norm_per_layer: 5
  l1_norm_activations_per_layer: 5
  learning_rate: 5
  max_attention_logits_all: 5
  max_attention_logits_per_layer: 5
  optimizer_stats: 5
  output_logits_max: 5
  output_logits_mean: 5
  total_gradient_norm: 5
  total_l1_norm: 5
  total_l2_norm: 5
  train_loss: 1
  validation_loss: 1
  weight_spectra_diff: 100
  weight_spectra_max: 100
  z_loss: 5

max_tokens: null
tokens_per_param: 10
max_train_steps: null
max_val_steps: 10
validate_every: 5

save_state_path: null
load_state_path: null
# NOTE: when loading a checkpoint from above, the below arguments are overwritten by the checkpoint
update_every_k: 10  # updates the checkpoints with the same name
save_every_k: null  # saves a new checkpoint state with a step added to name

seed: 444
