bias: true
block_size: 1024
n_embd: 256  
n_head: 8  
# head_size = n_embd // n_head = 256 // 8 = 32
n_layer: 3
n_query_groups: null
norm_class_name: LayerNorm
vocab_size: 50257
max_micro_batch_size: 9