bias: true
block_size: 1024
n_embd: 32  # scale0
n_head: 1  # scale0
# head_size = n_embd // n_head = 32 // 1 = 32
n_layer: 3
n_query_groups: null
norm_class_name: LayerNorm
vocab_size: 50257
max_micro_batch_size: 12